on:
  pull_request:
    branches:
      - main

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Maven version
        run: mvn - v

      - name: Maven test
        run: mvn test
        env:
          CI_RUN: true